feat: 회원가입 기능 구현
thenaun-workspace/simple-sns pull request #6
Opened 2021-03-06 16:58 UTC by YH3041

2021-03-07 00:45 UTC, thenaun-woody requested changes
저번에도 말씀드렸지만 브랜치명과 이슈번호의 관계에 대해서 다시 한번 생각해보셔요~
그리고 pr을 main에다가 보냈는데 여기다가 보내는게 맞나요~?

2021-03-07 00:45 UTC, thenaun-woody commented on src/main/java/com/younghoon/simplesns/controller/UserController.java
> +@RequiredArgsConstructor
현재는 인자가 하나라 별 문제가 없겠지만, RequiredArgsConstructor를 그냥 사용하면 버그가 발생할 수 있는 가능성이 있습니다. 어떤게 있을까요?

2021-03-07 00:45 UTC, thenaun-woody commented on src/main/java/com/younghoon/simplesns/controller/UserController.java
> +    @PostMapping("/signup/user")
path는 어떻게 작성하는게 좋을까요?
회원의 조회, 수정은 어떤 형태로 작성하실 계획이실까요?

2021-03-07 00:45 UTC, thenaun-woody commented on src/main/java/com/younghoon/simplesns/dto/UserDto.java
> +
컨벤션도 통일성 있게 작성부탁드려요~

2021-03-07 00:45 UTC, thenaun-woody commented on src/main/java/com/younghoon/simplesns/dto/UserDto.java
> +public class UserDto {
* user를 생성하는 요청을 담는 객체인거같아요. userId가 필요한건가요?
* 이 안에는 민감정보가 어떤게있을까요?
* 생성시각을 어디서 판단하는게 좋을까요? 같은 맥락으로 첫시도인데 수정시각도 같이 넘기는게 맞을까요?

2021-03-07 00:45 UTC, thenaun-woody commented on src/main/java/com/younghoon/simplesns/repository/UserRepository.java
> +    private static final Map<Long, UserDto> repository = new HashMap<>();
repository를 이렇게 관리를 하시는 이유가있을까요?
여러 요청이 동시에 접근하게되면 어떤 문제가 있을까요?

2021-03-07 00:45 UTC, thenaun-woody commented on src/test/java/com/younghoon/simplesns/repository/UserRepositoryTest.java
> +    UserRepository userRepository;
테스트가 깨지고있습니다. 어떤 이유일까요?

2021-03-07 05:41 UTC, YH3041 commented on src/main/java/com/younghoon/simplesns/controller/UserController.java
> +@RequiredArgsConstructor
- 인자가 2개이상 있을 때 필드 순서를 바꾸게되면 생성자 호출 시 값이 바뀌어 들어가는 문제점이 발생할 수 있네요 앞으로 참고하겠습니다

2021-03-07 10:13 UTC, YH3041 commented on src/main/java/com/younghoon/simplesns/controller/UserController.java
> +@RequiredArgsConstructor
- 인자가 2개이상 있을 때 필드 순서를 바꾸게되면 생성자 호출 시 값이 바뀌어 들어가는 문제점이 발생할 수 있네요! 앞으로 참고해서 사용하겠습니다!

2021-03-07 10:13 UTC, YH3041 commented on src/main/java/com/younghoon/simplesns/controller/UserController.java
> +    @PostMapping("/signup/user")
-예를들어 조회, 수정은 "/find", "/update" 이런식으로 각 기능에 맞게 path를 작성하는 게 좋을 것 같아서 그렇게 할 계획입니다!

2021-03-07 10:25 UTC, YH3041 commented on src/main/java/com/younghoon/simplesns/dto/UserDto.java
> +public class UserDto {
- userId 부분 수정하겠습니다.
- password 부분에 문제가 있는데 보안 관련 알아보겠습니다.
- 서버시간 입니다. 수정 시각은 필요 없을 거 같네요.

2021-03-07 10:29 UTC, YH3041 commented on src/main/java/com/younghoon/simplesns/repository/UserRepository.java
> +    private static final Map<Long, UserDto> repository = new HashMap<>();
- 기능 확인을 위해 필요하다고 판단해서 작성했습니다. DB 연결하는 방향으로 수정하겠습니다.
- Thread-Safe 하지 않습니다.

2021-03-07 10:29 UTC, YH3041 commented on src/test/java/com/younghoon/simplesns/repository/UserRepositoryTest.java
> +    UserRepository userRepository;
- 에러코드 확인해서 수정하겠습니다!

2021-03-07 10:33 UTC, closed without merging

2021-03-08 13:16 UTC, thenaun-woody commented on src/main/java/com/younghoon/simplesns/controller/UserController.java
> +    @PostMapping("/signup/user")
uri설계시 자원에 대한 상태값들을 표현해주어야한다고 같이 이야기를 했었는데요, 해당 관점으로 명명법이 저게 맞을지 한번 고민해보시고 다음번 pr때 이야기해보아요~

2021-03-08 13:17 UTC, thenaun-woody commented
넵 내용확인했습니다. 이야기 나눈대로 브랜치명, 기능범위 고려하셔서 다시 pr 올려주셔요~ ㅎㅎ